from models import db, Livro

def inicializar_catalogo():
    if not Livro.query.first():  # Só adiciona se a tabela estiver vazia
        catalogo_inicial = [
            Livro(titulo="Dom Casmurro", autor="Machado de Assis", preco=29.90,
                  descricao="Romance clássico brasileiro.", 
                  sinopse="Narrativa sobre ciúmes e traição no Rio de Janeiro do século XIX.",
                  autor_info="Machado de Assis (1839-1908) é um dos maiores escritores brasileiros."),
            Livro(titulo="1984", autor="George Orwell", preco=34.50,
                  descricao="Distopia sobre controle totalitário.", 
                  sinopse="Um homem luta contra um regime opressor em um futuro distópico.",
                  autor_info="George Orwell (1903-1950) foi um escritor e jornalista britânico."),
            Livro(titulo="O Senhor dos Anéis", autor="J.R.R. Tolkien", preco=59.90,
                  descricao="Épica fantasia de aventura.", 
                  sinopse="A jornada para destruir um anel poderoso em uma terra mítica.",
                  autor_info="J.R.R. Tolkien (1892-1973) foi um filólogo e escritor britânico."),
            Livro(titulo="Harry Potter e a Pedra Filosofal", autor="J.K. Rowling", preco=39.90,
                  descricao="Aventura mágica para jovens.", 
                  sinopse="Harry descobre ser um bruxo e entra em Hogwarts.",
                  autor_info="J.K. Rowling, autora britânica conhecida pela série Harry Potter."),
            Livro(titulo="O Pequeno Príncipe", autor="Antoine de Saint-Exupéry", preco=19.90,
                  descricao="Fábula poética e filosófica.", 
                  sinopse="Um piloto conhece um príncipe de outro planeta.",
                  autor_info="Antoine de Saint-Exupéry (1900-1944) foi um escritor e aviador francês."),
            Livro(titulo="Cem Anos de Solidão", autor="Gabriel García Márquez", preco=45.00,
                  descricao="Clássico do realismo mágico.", 
                  sinopse="A saga da família Buendía em um vilarejo colombiano.",
                  autor_info="Gabriel García Márquez (1927-2014) foi um Nobel de Literatura colombiano."),
            Livro(titulo="Orgulho e Preconceito", autor="Jane Austen", preco=28.50,
                  descricao="Romance de época sobre amor e classe.", 
                  sinopse="Elizabeth Bennet e Mr. Darcy superam preconceitos.",
                  autor_info="Jane Austen (1775-1817) foi uma romancista inglesa."),
            Livro(titulo="O Hobbit", autor="J.R.R. Tolkien", preco=32.90,
                  descricao="Aventura fantástica introdutória.", 
                  sinopse="Bilbo Baggins embarca em uma quest por tesouros.",
                  autor_info="J.R.R. Tolkien, mestre da literatura fantástica."),
            Livro(titulo="A Menina que Roubava Livros", autor="Markus Zusak", preco=36.75,
                  descricao="Drama na Segunda Guerra.", 
                  sinopse="Uma garota encontra refúgio nos livros durante o nazismo.",
                  autor_info="Markus Zusak é um escritor australiano contemporâneo."),
            Livro(titulo="Crime e Castigo", autor="Fiódor Dostoiévski", preco=42.30,
                  descricao="Clássico russo sobre culpa.", 
                  sinopse="Raskolnikov comete um crime e enfrenta sua consciência.",
                  autor_info="Fiódor Dostoiévski (1821-1881) foi um novelista russo."),
            Livro(titulo="O Alquimista", autor="Paulo Coelho", preco=24.90,
                  descricao="Fábula sobre autodescoberta.", 
                  sinopse="Um pastor segue seu sonho até o Egito.",
                  autor_info="Paulo Coelho é um renomado autor brasileiro."),
            Livro(titulo="As Crônicas de Gelo e Fogo: A Guerra dos Tronos", autor="George R.R. Martin", preco=55.00,
                  descricao="Fantasia épica e política.", 
                  sinopse="Lutas pelo trono em um mundo medieval fantástico.",
                  autor_info="George R.R. Martin é um escritor americano de fantasia."),
            Livro(titulo="Drácula", autor="Bram Stoker", preco=30.00,
                  descricao="Clássico do terror gótico.", 
                  sinopse="A luta contra o vampiro Conde Drácula.",
                  autor_info="Bram Stoker (1847-1912) foi um escritor irlandês."),
            Livro(titulo="A Revolução dos Bichos", autor="George Orwell", preco=22.50,
                  descricao="Sátira política em forma de fábula.", 
                  sinopse="Animais tomam uma fazenda e criam sua própria sociedade.",
                  autor_info="George Orwell, conhecido por suas críticas sociais."),
            Livro(titulo="O Código Da Vinci", autor="Dan Brown", preco=38.90,
                  descricao="Thriller de conspirações.", 
                  sinopse="Um simbologista desvenda mistérios da história cristã.",
                  autor_info="Dan Brown é um autor americano de thrillers."),
            Livro(titulo="Memórias Póstumas de Brás Cubas", autor="Machado de Assis", preco=27.80,
                  descricao="Narrativa inovadora e satírica.", 
                  sinopse="Um morto narra sua vida com humor ácido.",
                  autor_info="Machado de Assis, ícone da literatura brasileira."),
            Livro(titulo="O Mundo de Sofia", autor="Jostein Gaarder", preco=33.60,
                  descricao="Introdução à filosofia.", 
                  sinopse="Uma garota aprende história da filosofia através de cartas.",
                  autor_info="Jostein Gaarder é um escritor norueguês."),
            Livro(titulo="Percy Jackson e o Ladrão de Raios", autor="Rick Riordan", preco=29.50,
                  descricao="Mitologia grega moderna.", 
                  sinopse="Um jovem descobre ser filho de Poseidon.",
                  autor_info="Rick Riordan é um autor americano de literatura infantojuvenil."),
            Livro(titulo="A Sombra do Vento", autor="Carlos Ruiz Zafón", preco=41.20,
                  descricao="Mistério literário.", 
                  sinopse="Um garoto busca o autor de um livro misterioso.",
                  autor_info="Carlos Ruiz Zafón foi um escritor espanhol."),
            Livro(titulo="O Processo", autor="Franz Kafka", preco=35.00,
                  descricao="Clássico da literatura existencial.", 
                  sinopse="Um homem enfrenta um julgamento absurdo.",
                  autor_info="Franz Kafka (1883-1924) foi um escritor tcheco.")
        ]
        for livro in catalogo_inicial:
            db.session.add(livro)
        db.session.commit()